### ISSUE TITLE
Todo: PoC to Application

### ISSUE THREAD

**Issue by Hufschmidt** [Hufschmidt/KenkuChat#1]
- [ ] Refactor and split index.ts into logical component
- [ ] Extract KenkuFM api into component
- [ ] Implement logging via pino library
- [ ] Think about better/best discord command list
- [ ] Ensure that user-input is **always** checked and sanitised
- [ ] Convert config.json into yargs arguments
- [ ] Implement more error-handling (and error-logging!)
- [ ] Implement search/autocomplete option (eg. using Fuse.js)
- [ ] Support answering with matched list when multiple titles have been found
- [ ] Think about permissions and multi-user, multi-bot cases
